string a = "Welcome C# Example";
string b = "C# Example ";
Console.WriteLine(a.Length);
Console.WriteLine(a.ToLower());
Console.WriteLine(a.ToUpper());
Console.WriteLine(String.Concat(a,"Welcome"));
Console.WriteLine(a.CompareTo(b));
Console.WriteLine(String.Compare(a,b,true));
Console.WriteLine(String.Compare(a,b,false));
Console.WriteLine(a.Contains(b));
Console.WriteLine(a.EndsWith("Example"));
Console.WriteLine(a.StartsWith("Welcome"));
Console.WriteLine(a.IndexOf("C#"));
Console.WriteLine(a.IndexOf("Berk"));
Console.WriteLine(a.Insert(0,"Hello,"));
Console.WriteLine(a.LastIndexOf("a"));
Console.WriteLine(a.Remove(10));
Console.WriteLine(a.Remove(5, 3));
Console.WriteLine(a.Replace("C#", "CSharp"));
Console.WriteLine(a.Replace(" ","+"));
Console.WriteLine(a.Split(' ')[1]);
Console.WriteLine(a.Substring(4));
Console.WriteLine(a.Substring(4,6));